### ISSUE TITLE
Feature Request: Add support for lspkind to show icon?

### ISSUE THREAD

**Issue by Peeeaje** [chrisgrieser/cmp_yanky#3]
### Feature Requested

Firstly I really love the plugin, thank you.

My concern is that, I'd like to get integration with lsp kind to show icon. Is it possible at the moment?
I just confirmed by adding this code in `cmp_yanky.lua` it works as expected. I don't know such work is needed for showing icon to work though.

```
cmp = {
    kind_hl_group = "CmpItemKindYanky",
    kind_text = 'Yanky',
},
```

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Thanks!

So, adding icons to is not really something that is special to this plugin, the method is the same for any cmp-plugin. You (or lspkind) defines the formatting somewhere in `require("cmp").setup({ formatting = … })`. 

I'd refer to the[ cmp wiki](https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance) or the lspkind docs for how to change icons for particular sources.

Closing this, since this is not related to this plugin, but rather a general cmp question.
