### ISSUE TITLE
[Bug]: Failed to run `config` for cmp_yanky

### ISSUE THREAD

**Issue by shauryagoel** [chrisgrieser/cmp_yanky#4]
### Bug Description

I tried to add the following config to my setup using lazy.nvim-

```
  {
    "nvim-cmp",
    dependencies = {
      { "chrisgrieser/cmp_yanky", opts = {} },
    },
    ---@module 'cmp'
    ---@param opts cmp.ConfigSchema
    opts = function(_, opts)
      table.insert(opts.sources, { name = "cmp_yanky" })
    end,
  },
```
After loading the `nvim-cmp`, I get the following error-
```
Failed to run `config` for cmp_yanky

...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:383: attempt to call field 'setup' (a nil value)
```

### neovim version

```Text
0.10.1
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
The issue is with this line: `{ "chrisgrieser/cmp_yanky", opts = {} },`, which should just be `{ "chrisgrieser/cmp_yanky" },`.

cmp plugins work a little different from your "regular" nvim plugin, they mostly do not have a `setup` call and thus also not `opts` for lazy.nvim. Instead, you configure them via `options`.

I expanded the [respective section in the readme a bit, to make it more clear](https://github.com/chrisgrieser/cmp_yanky?tab=readme-ov-file#options).
